{% set name = "pCrunch" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/pCrunch/archive/v{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pCrunch-{{ version }}.tar.gz
  sha256: 55a417bd4c17fd8489cc9037686290990d8e37a0c4631c0e587bda53cb8c59f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -v
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - fatpack
    - numexpr
    - numpy
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - ruamel.yaml
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pCrunch
  source_files:
    - pCrunch
    - examples
  commands:
    - cd examples
    - python example_casematrix.py
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/nrel/pcrunch
  summary: "IO and Post Processing Interface for OpenFAST Results."
  description: |
    Python utilities and scripts for ultimate load tables and fatigue damage
    equivalent life (DEL) calculation for OpenFAST aeroelastic time-series simulations
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/nrel/pcrunch

extra:
  recipe-maintainers:
    - gbarter
    - jakenunemaker
