{% set name = "pCrunch" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/pCrunch/archive/v{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pCrunch-{{ version }}.tar.gz
  sha256: b5da4e2abb82b4251fc0bab61d43821f47262997a169a065545f366745cdace8
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - fatpack
    - numpy
    - pandas
    - python >=3.9
    - pyyaml
    - scipy

test:
  imports:
    - pCrunch
  #commands:
  #  - pytest pCrunch
  #requires:
  #  - pytest

about:
  home: https://github.com/nrel/pcrunch
  summary: "IO and Post Processing Interface for OpenFAST Results."
  description: |
      Python utilities and scripts for ultimate load tables and fatigue damage
      equivalent life (DEL) calculation for OpenFAST aeroelastic time-series simulations
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/nrel/pcrunch

extra:
  recipe-maintainers:
    - gbarter
    - jakenunemaker
