{% set name = "pCrunch" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/pCrunch/archive/v{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pCrunch-{{ version }}.tar.gz
  sha256: 6c4a42de8f1a3c1459b4af3b3d3041868efeb1752a3ccb15afeff2b2c4ab53ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -v
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - fatpack
    - numexpr
    - numpy
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - ruamel.yaml
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pCrunch
  commands:
    - pytest pCrunch
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/nrel/pcrunch
  summary: "IO and Post Processing Interface for OpenFAST Results."
  description: |
    Python utilities and scripts for ultimate load tables and fatigue damage
    equivalent life (DEL) calculation for OpenFAST aeroelastic time-series simulations
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/nrel/pcrunch

extra:
  recipe-maintainers:
    - gbarter
    - jakenunemaker
