{% set name = "pCrunch" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nrel/pCrunch/archive/v{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pCrunch-{{ version }}.tar.gz
  sha256: 83335d4fc1f5ab1e34a5337294b04157d68cdb4968c014c47c7ae408d42069b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -v
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - fatpack
    - numexpr
    - numpy
    - pandas
    - python >={{ python_min }}
    - pyyaml
    - ruamel.yaml
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - pCrunch
  source_files:
    - pCrunch
    - examples
  commands:
    - cd examples
    - python example_casematrix.py

about:
  home: https://github.com/nrel/pcrunch
  summary: "IO and Post Processing Interface for OpenFAST Results."
  description: |
    Python utilities and scripts for ultimate load tables and fatigue damage
    equivalent life (DEL) calculation for OpenFAST aeroelastic time-series simulations
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/nrel/pcrunch

extra:
  recipe-maintainers:
    - gbarter
    - jakenunemaker
